"""
Integration tests for api/server.py.

The gRPC server and TorchServe are tested in isolation:
- gRPC stubs are generated from emotion.proto by conftest.py.
- TorchServe HTTP calls are intercepted via a patched httpx.AsyncClient.
- No real gRPC socket is opened; we call the servicer methods directly.
"""
from __future__ import annotations

import json
from unittest.mock import AsyncMock, MagicMock, patch

import httpx
import pytest

import emotion_pb2  # generated by conftest.py
from api.server import EmotionServicer
from api.schemas import InferenceResponse
from config.settings import Settings


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _settings(**overrides) -> Settings:
    base = dict(
        grpc_port=50051,
        torchserve_host="localhost",
        torchserve_inference_port=8080,
        model_name="emotion-detector",
    )
    base.update(overrides)
    return Settings(**base)


def _ts_response(**kwargs) -> httpx.Response:
    """Build a fake TorchServe HTTP 200 response."""
    defaults = dict(
        session_id="s1",
        dominant_emotion="happy",
        confidence_scores={"happy": 0.9},
        stress=0.1,
        engagement=0.8,
        arousal=0.5,
        overall_confidence=0.9,
        embedding=[0.0] * 512,
        timestamp_ms=1000,
        buffering=False,
        error="",
    )
    defaults.update(kwargs)
    return httpx.Response(200, json=defaults)


def _make_request(**kwargs) -> emotion_pb2.EmotionRequest:
    defaults = dict(
        session_id="s1",
        video_frame=b"\x00" * (4 * 4 * 3),
        frame_width=4,
        frame_height=4,
        timestamp_ms=1000,
    )
    defaults.update(kwargs)
    return emotion_pb2.EmotionRequest(**defaults)


async def _iter(*items):
    for item in items:
        yield item


# ---------------------------------------------------------------------------
# Tests: StreamEmotion happy path
# ---------------------------------------------------------------------------

class TestStreamEmotionHappyPath:
    async def test_single_frame_returns_result(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "post", new_callable=AsyncMock) as mock_post:
            mock_post.return_value = _ts_response()
            context = MagicMock()

            responses = []
            async for resp in servicer.StreamEmotion(_iter(_make_request()), context):
                responses.append(resp)

        assert len(responses) == 1
        assert responses[0].dominant_emotion == "happy"
        assert responses[0].session_id == "s1"
        assert responses[0].buffering is False
        assert responses[0].error == ""

    async def test_embedding_propagated(self):
        settings = _settings()
        servicer = EmotionServicer(settings)
        embedding = [float(i) for i in range(512)]

        with patch.object(servicer._http, "post", new_callable=AsyncMock) as mock_post:
            mock_post.return_value = _ts_response(embedding=embedding)
            context = MagicMock()

            responses = []
            async for resp in servicer.StreamEmotion(_iter(_make_request()), context):
                responses.append(resp)

        assert list(responses[0].embedding) == pytest.approx(embedding)

    async def test_multiple_frames(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "post", new_callable=AsyncMock) as mock_post:
            mock_post.return_value = _ts_response()
            context = MagicMock()

            requests = _iter(
                _make_request(timestamp_ms=1000),
                _make_request(timestamp_ms=2000),
                _make_request(timestamp_ms=3000),
            )
            responses = []
            async for resp in servicer.StreamEmotion(requests, context):
                responses.append(resp)

        assert len(responses) == 3
        assert mock_post.call_count == 3


# ---------------------------------------------------------------------------
# Tests: buffering
# ---------------------------------------------------------------------------

class TestStreamEmotionBuffering:
    async def test_buffering_response_forwarded(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "post", new_callable=AsyncMock) as mock_post:
            mock_post.return_value = _ts_response(
                buffering=True,
                dominant_emotion="",
                confidence_scores={},
                embedding=[],
            )
            context = MagicMock()

            responses = []
            async for resp in servicer.StreamEmotion(_iter(_make_request()), context):
                responses.append(resp)

        assert responses[0].buffering is True
        assert responses[0].dominant_emotion == ""


# ---------------------------------------------------------------------------
# Tests: error handling
# ---------------------------------------------------------------------------

class TestStreamEmotionErrors:
    async def test_torchserve_connect_error_yields_error_response(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "post", new_callable=AsyncMock) as mock_post:
            mock_post.side_effect = httpx.ConnectError("refused")
            context = MagicMock()

            responses = []
            async for resp in servicer.StreamEmotion(_iter(_make_request()), context):
                responses.append(resp)

        assert len(responses) == 1
        assert "unavailable" in responses[0].error.lower()

    async def test_torchserve_http_500_yields_error_response(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "post", new_callable=AsyncMock) as mock_post:
            mock_post.return_value = httpx.Response(500, text="internal error")
            context = MagicMock()

            responses = []
            async for resp in servicer.StreamEmotion(_iter(_make_request()), context):
                responses.append(resp)

        assert "500" in responses[0].error

    async def test_handler_error_field_propagated(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "post", new_callable=AsyncMock) as mock_post:
            mock_post.return_value = _ts_response(error="model exploded", dominant_emotion="")
            context = MagicMock()

            responses = []
            async for resp in servicer.StreamEmotion(_iter(_make_request()), context):
                responses.append(resp)

        assert responses[0].error == "model exploded"

    async def test_session_cleanup_called_on_stream_close(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "post", new_callable=AsyncMock) as mock_post:
            mock_post.return_value = _ts_response()
            context = MagicMock()

            async for _ in servicer.StreamEmotion(_iter(_make_request()), context):
                pass

        # cleanup is the second post call (first is inference)
        assert mock_post.call_count == 2
        cleanup_call = mock_post.call_args_list[1]
        body = cleanup_call.kwargs.get("json") or cleanup_call.args[1] if len(cleanup_call.args) > 1 else cleanup_call.kwargs["json"]
        assert body["action"] == "cleanup"
        assert body["session_id"] == "s1"

    async def test_session_cleanup_called_even_on_error(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "post", new_callable=AsyncMock) as mock_post:
            mock_post.side_effect = httpx.ConnectError("refused")
            context = MagicMock()

            responses = []
            async for resp in servicer.StreamEmotion(_iter(_make_request()), context):
                responses.append(resp)

        # First call raised ConnectError (yielded error response),
        # second call is cleanup (also will raise, but non-fatal).
        assert mock_post.call_count >= 2


# ---------------------------------------------------------------------------
# Tests: HealthCheck
# ---------------------------------------------------------------------------

class TestHealthCheck:
    async def test_healthy_when_torchserve_returns_200(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "get", new_callable=AsyncMock) as mock_get:
            mock_get.return_value = httpx.Response(200, json={"status": "Healthy"})
            resp = await servicer.HealthCheck(emotion_pb2.HealthRequest(), MagicMock())

        assert resp.healthy is True
        assert resp.model_status == "ready"

    async def test_unhealthy_when_torchserve_returns_503(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "get", new_callable=AsyncMock) as mock_get:
            mock_get.return_value = httpx.Response(503)
            resp = await servicer.HealthCheck(emotion_pb2.HealthRequest(), MagicMock())

        assert resp.healthy is False
        assert resp.model_status == "unavailable"

    async def test_unhealthy_when_torchserve_unreachable(self):
        settings = _settings()
        servicer = EmotionServicer(settings)

        with patch.object(servicer._http, "get", new_callable=AsyncMock) as mock_get:
            mock_get.side_effect = httpx.ConnectError("refused")
            resp = await servicer.HealthCheck(emotion_pb2.HealthRequest(), MagicMock())

        assert resp.healthy is False
        assert resp.model_status == "unreachable"
